### ISSUE TITLE
Support For Locals Or Custom Properties

### ISSUE THREAD

**Issue by LuisOsta** [bikk-uk/jest-mock-express#27]
Hi,
In express, you can pass objects between middleware through either adding your custom property to the request object or through the local property provided.

This mock doesn't provide support for either approach.
Would it be possible to add support to one (or both ideally)?

The locals approach would look a bit like this:
```
const req = getMockReq({locals: {var: "hi there"}})
```

**Comment by aboyce** [comment]
Hello,

Yep, that is a good spot and I agree it would be useful to include 👍 

I have started adding this in and it looks to be working as expected. Just as a heads up, `locals` only appears to be 'officially' valid on the `res` object according to the [express docs](https://expressjs.com/en/api.html#res.locals).

For the implementation of this:

**`req`**
Custom properties can now be passed through to the returned object. As it returns an `express` typed `Request`, casting might be required as custom properties will not exist on that. In dev/testing, it seemed to be fine though and it was only the libraries tests where I had to cast, not on a separate project consuming the library.

```typescript
const req = getMockReq({
  user: getMockUser()
  // can provide anything here
})
```

**`res`**
Any values that were previously provided with default values will be typed (this includes `locals`), and then you can just provide anything custom ontop of this.

The example implementation will look like how you mentioned:

```typescript
const { res, next } = getMockRes({
  locals: {
    isPremiumUser: true
  },
  var: 'hi there'
  // can provide anything here
})
```

It should hopefully be released as a new version over the next few days after further tests and when the documentation has been updated 👍

**Comment by LuisOsta** [comment]
Thanks! That sounds great.
On the locals thing after further review, you're completely right. It's interesting that most popular posts mention the various ways you can configure locals ( I think there are like four) but only the response one is considered official

Regardless I think the implementation you described is spot on.
