### ISSUE TITLE
.status() not chaining

### ISSUE THREAD

**Issue by CrypticSafe5** [bikk-uk/jest-mock-express#58]
I noticed that when my app had a chained response like so:
```javascript
response.status(204).send();
```
the tests would fail because `status()` is returning undefined in the tests, while really it returns a reference to `this` enabling it to chain.

To get it to chain properly in my tests I had to implement the following:
```javascript
// Top of test file
const mockedStatusFunc = jest.fn();
const mockedResponse = getMockRes({ status: mockedStatusFunc });
// In my tests
mockedStatusFunc.mockReturnThis();
```
I did notice though that it worked just fine if I didn't chain the functions together which is what led me to this conclusion.
```javascript
// Worked
response.status(204);
response.send();
// Doesn't work
response.status(204).send();
```

**Comment by aboyce** [comment]
Hello @CrypticSafe5,

I've had a play about and it seems to be behaving as expected for me, are you still seeing this problem?

The `res.status` function is definitely returning itself as part of it's default implementation.

https://github.com/bikk-uk/jest-mock-express/blob/4bd710190f858de615f72eba1a7ddce29c597e74/src/response/response.ts#L103

I have added an example in a sandbox repo and it seems to be ok with the `status` and then `send` chain example you provided.

https://github.com/aboyce/jest-mock-express-sandbox/commit/4f9d73cd4d2aad5cb4bd614dc912cc7618039272

**Comment by CrypticSafe5** [comment]
I am. I wonder if it's the ts-jest configuration I have. It seems to be different than what you are running. For reference I currently have:
```jsonc
// package.json
{
  // ...
  "jest": {
    "preset": "ts-jest",
    "roots": [
      "<rootDir>/src"
    ],
    "resetMocks": true
  }
}
```

and [your tests](https://github.com/aboyce/jest-mock-express-sandbox/blob/master/jest.config.js) run with:

```javascript
// jest.config.js
const tsPreset = require('ts-jest/jest-preset')

const ignorePatterns = [
  '<rootDir>/node_modules',
  '<rootDir>/dist',
  '<rootDir>/src/models',
  '<rootDir>/src/helpers',
  '<rootDir>/src/routers',
  '<rootDir>/src/services',
]

const optionOverrides = {
  testEnvironment: 'node',
  testPathIgnorePatterns: ignorePatterns,
  coveragePathIgnorePatterns: ignorePatterns,
}

module.exports = { ...tsPreset, ...optionOverrides }
```

I'll test with your configuration and see if it makes a difference.

**Comment by tomhalley** [comment]
Have run into this issue, @CrypticSafe5 did you manage to fix it?

**Comment by alagunoff** [comment]
Run into the same issue

**Comment by arlgnv** [comment]
> Have run into this issue, @CrypticSafe5 did you manage to fix it?

Hi. I managed. Instead of creating mock response at the top of a module, I'm creating it inside each suite. Otherwise I got the same error
![image](https://github.com/bikk-uk/jest-mock-express/assets/46949445/a2baf13b-ccba-4fc9-849f-93e107801e5b)

**Comment by arlgnv** [comment]
@aboyce 
I do not know why either, but `mockRes` object doesn't work properly. It seems that its methods do not return response object back
![image](https://github.com/bikk-uk/jest-mock-express/assets/46949445/8366e72d-dc32-4717-acdc-8e3759179dcb)
