### ISSUE TITLE
Needs implement headers on Request.

### ISSUE THREAD

**Issue by alycioneto** [bikk-uk/jest-mock-express#6]
Hi! I'm using your lib in my TS project, thank you so much, it has been very usefull! But there is a little problem when I try to test headers. As you can see in this link [Request](https://github.com/expressjs/express/blob/18da651c5b57431f61391d9de2518a8c2ef88b2c/lib/request.js#L31), express Request implements IncomingMessage, and they have a property called headers, and I had trouble testing this, I’m sending some screen shots so that you can understand the problem.
![Captura de Tela 2020-05-29 às 19 39 18](https://user-images.githubusercontent.com/18275872/83311825-d23d3c80-a1e6-11ea-9254-16db53763bc4.png)
![Captura de Tela 2020-05-29 às 19 39 39](https://user-images.githubusercontent.com/18275872/83311839-d8cbb400-a1e6-11ea-98b1-46f5fea116ea.png)
![Captura de Tela 2020-05-29 às 19 40 01](https://user-images.githubusercontent.com/18275872/83311848-dec19500-a1e6-11ea-9cb4-01ea92df3278.png)
![Captura de Tela 2020-05-29 às 19 40 10](https://user-images.githubusercontent.com/18275872/83311852-e1bc8580-a1e6-11ea-825f-2ff46d3f67d6.png)

**Comment by aboyce** [comment]
Hello, thank you for using the library, I am glad you find it useful!

Yep, this is a great point and thank you for providing details/examples. I will resolve this and it will be fixed in an upcoming release. I will let you know when it will be resolved, should be later today 👍

**Comment by aboyce** [comment]
> Hello, thank you for using the library, I am glad you find it useful!
> 
> Yep, this is a great point and thank you for providing details/examples. I will resolve this and it will be fixed in an upcoming release. I will let you know when it will be resolved, should be later today 👍

@alycioneto, this should now be resolved in release 0.9.6 😃 Please let us know if this does not resolve the issue for you and feel free to continue raising issues if you notice more things you would like adding 👍

**Comment by alycioneto** [comment]
Thank so much, Adam! It's working perfectly now! Thanks for the availability and speed in this implementation.
