### ISSUE TITLE
Provide a way to store the data in the response object

### ISSUE THREAD

**Issue by paztis** [bikk-uk/jest-mock-express#66]
currently the only way to test the data is to call
```
expect(res.send).toHaveBeenCalledWith(...)
expect(res.json).toHaveBeenCalledWith(...)
expect(res.end).toHaveBeenCalledWith(...)
```

I may be important to store the data in you mock to let it be accessed with 
expect(res.data).toBe(...)

It may be done in your mock by saving the args of the send / josn / end

**Comment by rdimascio** [comment]
You can access the data returned with `res.json.mock.calls[0][0]`

**Comment by Joshandrews43** [comment]
> You can access the data returned with `res.json.mock.calls[0][0]`

This does not work: 

```import { getMockReq, getMockRes } from '@jest-mock/express';
import handler from './handler';

describe('Basic express test example', () => {
  it('returns pong', async () => {
    const req = getMockReq();
    const { res } = getMockRes();
    await handler.ping(req, res); // (_, res) => res.send('pong');
    const response = res.json.mock.calls[0][0] // is empty array
    expect(response).toBe("pong");
  });
});
```

**Comment by aboyce** [comment]
Closing this now as it's gone stale and an answer has been provided.
